<?php

/**
 * @file
 * Primary module hooks for NYPL Cards module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function nypl_cards_entity_bundle_field_info_alter(array &$fields,EntityTypeInterface $entity_type,
  $bundle) {
  // You can add constraints to bundle-specific fields of entities defined by
  // other modules using this hook. For example, the code below adds a
  // constraint to the "field_start/end_date" of "nypl_card" nodes.
  if (
    $entity_type->id() === 'node' &&
    $bundle === 'nypl_card' &&
    (isset($fields['field_start_date']) || isset($fields['field_end_date']))
  ) {
    $fields['field_start_date']->addConstraint('WeekdayDate', []);
    $fields['field_end_date']->addConstraint('WeekdayDate', []);
  }
}